Om 24 change a class to be a container
i-doit/docs pull request #43
Opened 2022-08-16 08:37 UTC by MartinHartkopf

Short description Custom Classes

Long definition of custom classes and how to create them

2022-08-16 08:41 UTC, MartinHartkopf commented
Definition of custom Classes

2022-08-17 08:02 UTC, MichaelOv requested changes

2022-08-17 08:02 UTC, MichaelOv commented on docs/admin/custom-classes.md
> +# custom classes
Headings always begin with uppercase letters

2022-08-17 08:02 UTC, MichaelOv commented on docs/admin/custom-classes.md
> +# add custom classes
Headings always begin with uppercase letters

2022-08-17 08:02 UTC, MichaelOv commented on docs/admin/custom-classes.md
> +# customizing custom classes
Headings always begin with uppercase letters

2022-08-22 13:14 UTC, MichaelOv approved these changes

2022-12-12 09:44 UTC, merged